[tool.poetry]
name = "hnefatafl"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "hnefatafl", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.24.1"
pyglet = "^2.0.3"
neat-python = "^0.92"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
black = "^22.12.0"
pytest-mock = "^3.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
